<a href="https://colab.research.google.com/github/Carchives03/NYCSummonsPracticeData/blob/main/CT_dynamic_scrapes_blank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Javascript Dynamic Scrapes

Example sites:
- <a href="https://a816-health.nyc.gov/ABCEatsRestaurants/#!/Search">Restaurant Inspections</a>
- <a href="https://www1.nyc.gov/site/doh/health/health-topics/school-cafeteria-inspection-results.page">School cafeteria Inspections</a>

Try one page first

In [2]:
url = "https://a816-health.nyc.gov/ABCEatsRestaurants/App/GetEntitiesByBoro/Manhattan"

In [3]:
import pandas as pd
import requests

In [4]:
response = requests.get(url)

In [5]:
response.json()

[{'EntityName': '"U" LIKE CHINESE TAKE OUT',
  'Cuisine': 'Chinese',
  'CurrentDecalNumber': '50126747',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10034',
  'MostRecent_Longitude': -73.921726346618,
  'MostRecent_Latitude': 40.867494224968,
  'Grade': 'A',
  'MostRecentVendingLocation': '4926 BROADWAY'},
 {'EntityName': '$1 PIZZA',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '50117047',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10014',
  'MostRecent_Longitude': -74.001176261932,
  'MostRecent_Latitude': 40.731408835598,
  'Grade': 'Grade Pending',
  'MostRecentVendingLocation': '333B AVENUE OF THE AMERICAS'},
 {'EntityName': '$1 PIZZA',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '50086385',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10001',
  'MostRecent_Longitude': -73.990158293876,
  'MostRecent_Latitude': 40.746510107881,
  'Grade': 'A',
  'MostRecentVendingLocation': '832 6 AVENUE'},
 {'EntityName': '$1.50 FRESH PIZZA',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '50136410',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10019',
  'MostRecent_Longitude': -73.982303947291,
  'MostRecent_Latitude': 40.764514788457,
  'Grade': 'A',
  'MostRecentVendingLocation': '1723 BROADWAY'},
 {'EntityName': '$1.50 FRESH PIZZA',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '50136412',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10013',
  'MostRecent_Longitude': -74.00474041648,
  'MostRecent_Latitude': 40.721426029021,
  'Grade': 'A',
  'MostRecentVendingLocation': '383 CANAL STREET'},
 {'EntityName': '$1.50 FRESH PIZZA',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '50136418',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10003',
  'MostRecent_Longitude': -73.989331471843,
  'MostRecent_Latitude': 40.726325039467,
  'Grade': 'A',
  'MostRecentVendingLocation': '71 2 AVENUE'},
 {'EntityName': '$1.50 FRESH PIZZA & HOT DOG',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '50105651',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10009',
  'MostRecent_Longitude': -73.982992285603,
  'MostRecent_Latitude': 40.72681284306,
  'Grade': 'B',
  'MostRecentVendingLocation': '131 AVENUE A'},
 {'EntityName': '$1.50 PIZZA SLICE',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '50153086',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10019',
  'MostRecent_Longitude': -73.988765921819,
  'MostRecent_Latitude': 40.76371413372,
  'Grade': 'B',
  'MostRecentVendingLocation': '748 9 AVENUE'},
 {'EntityName': '% ARABICA',
  'Cuisine': 'Middle Eastern',
  'CurrentDecalNumber': '50170934',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10019',
  'MostRecent_Longitude': -73.976684256964,
  'MostRecent_Latitude': 40.761593362017,
  'Grade': 'Grade Pending',
  'MostRecentVendingLocation': '37 WEST   54 STREET'},
 {'EntityName': '% Arabica',
  'Cuisine': 'Coffee/Tea',
  'CurrentDecalNumber': '50170936',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10112',
  'MostRecent_Longitude': -73.978692223615,
  'MostRecent_Latitude': 40.758747437799,
  'Grade': 'B',
  'MostRecentVendingLocation': '30 ROCKEFELLER PLAZA'},
 {'EntityName': '& SON',
  'Cuisine': 'Steakhouse',
  'CurrentDecalNumber': '50126158',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10011',
  'MostRecent_Longitude': -73.998585544932,
  'MostRecent_Latitude': 40.733953229906,
  'Grade': 'A',
  'MostRecentVendingLocation': '62 WEST    9 STREET'},
 {'EntityName': "'ESSEN",
  'Cuisine': 'American',
  'CurrentDecalNumber': '50178828',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10017',
  'MostRecent_Longitude': -73.980004612489,
  'MostRecent_Latitude': 40.751828134763,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '290 MADISON AVENUE'},
 {'EntityName': "'RITAS",
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50182395',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10019',
  'MostRecent_Longitude': -73.988625101441,
  'MostRecent_Latitude': 40.763908997638,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '756 9 AVENUE'},
 {'EntityName': ':3 COFFEE',
  'Cuisine': 'Coffee/Tea',
  'CurrentDecalNumber': '50134736',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10010',
  'MostRecent_Longitude': -73.991638705565,
  'MostRecent_Latitude': 40.740737990032,
  'Grade': 'A',
  'MostRecentVendingLocation': '29 WEST   21 STREET'},
 {'EntityName': '1 EAST 66TH STREET KITCHEN',
  'Cuisine': 'American',
  'CurrentDecalNumber': '40359480',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10065',
  'MostRecent_Longitude': -73.969580578452,
  'MostRecent_Latitude': 40.768546914232,
  'Grade': 'A',
  'MostRecentVendingLocation': '1 EAST   66 STREET'},
 {'EntityName': '1 FABENE',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '50158107',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10030',
  'MostRecent_Longitude': -73.943464105864,
  'MostRecent_Latitude': 40.81560400718,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '2309 ADAM CLAYTON POWELL JR BOULEVARD'},
 {'EntityName': '1 HOTEL CENTRAL PARK',
  'Cuisine': 'American',
  'CurrentDecalNumber': '50166828',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10019',
  'MostRecent_Longitude': -73.976845586201,
  'MostRecent_Latitude': 40.764780058501,
  'Grade': 'A',
  'MostRecentVendingLocation': '1414 AVENUE OF THE AMERICAS'},
 {'EntityName': '1 STOP PATTY SHOP',
  'Cuisine': 'Bakery Products/Desserts',
  'CurrentDecalNumber': '41430594',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10031',
  'MostRecent_Longitude': -73.947878825434,
  'MostRecent_Latitude': 40.824869602416,
  'Grade': 'A',
  'MostRecentVendingLocation': '1708 AMSTERDAM AVENUE'},
 {'EntityName': '1.50 PIZZA',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '50158801',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10036',
  'MostRecent_Longitude': -73.991842090937,
  'MostRecent_Latitude': 40.759523147973,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '617 9 AVENUE'},
 {'EntityName': '1.50 PIZZA & EMPANADAS',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '50172476',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10033',
  'MostRecent_Longitude': -73.932935315983,
  'MostRecent_Latitude': 40.848971629693,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '558 WEST  181 STREET'},
 {'EntityName': '100 FEAST & LOUNGE',
  'Cuisine': 'Chinese',
  'CurrentDecalNumber': '50180638',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10002',
  'MostRecent_Longitude': -73.993406023502,
  'MostRecent_Latitude': 40.71379273744,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '100 EAST BROADWAY'},
 {'EntityName': '100 MARKET PLACE',
  'Cuisine': 'American',
  'CurrentDecalNumber': '50145138',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10004',
  'MostRecent_Longitude': -74.011606197564,
  'MostRecent_Latitude': 40.703504942078,
  'Grade': 'B',
  'MostRecentVendingLocation': '100 BROAD STREET'},
 {'EntityName': '101 DYCKMAN PESCADERIA INC',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50179313',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10040',
  'MostRecent_Longitude': -73.924845853614,
  'MostRecent_Latitude': 40.861770801137,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '101 DYCKMAN STREET'},
 {'EntityName': '1020 BAR',
  'Cuisine': 'American',
  'CurrentDecalNumber': '50147296',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10025',
  'MostRecent_Longitude': -73.963781811583,
  'MostRecent_Latitude': 40.803093425955,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '1020 AMSTERDAM AVENUE'},
 {'EntityName': '10455',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50186487',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10040',
  'MostRecent_Longitude': -73.930157415288,
  'MostRecent_Latitude': 40.854215160835,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '1579 SAINT NICHOLAS AVENUE'},
 {'EntityName': '106 NUTRITION BLENDS',
  'Cuisine': 'Juice, Smoothies, Fruit Salads',
  'CurrentDecalNumber': '50129829',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10029',
  'MostRecent_Longitude': -73.945553643185,
  'MostRecent_Latitude': 40.791942547949,
  'Grade': 'A',
  'MostRecentVendingLocation': '167 EAST  106 STREET'},
 {'EntityName': '107 DAILY & GRILL',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50107755',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10025',
  'MostRecent_Longitude': -73.965101189285,
  'MostRecent_Latitude': 40.801243874539,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '963 AMSTERDAM AVENUE'},
 {'EntityName': '108 DYCKMAN FINEST DELI & GRILL INC',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50179260',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10040',
  'MostRecent_Longitude': -73.924972207567,
  'MostRecent_Latitude': 40.861930078051,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '108 DYCKMAN STREET'},
 {'EntityName': '109 PIZZERIA',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '50135924',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10029',
  'MostRecent_Longitude': -73.943468732239,
  'MostRecent_Latitude': 40.793231573165,
  'Grade': 'A',
  'MostRecentVendingLocation': '1976 3 AVENUE'},
 {'EntityName': '10TH AVENUE COOKSHOP',
  'Cuisine': 'American',
  'CurrentDecalNumber': '41092609',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10011',
  'MostRecent_Longitude': -74.005637163453,
  'MostRecent_Latitude': 40.745645791526,
  'Grade': 'A',
  'MostRecentVendingLocation': '156 10 AVENUE'},
 {'EntityName': '10TH AVENUE PIZZA & CAFE',
  'Cuisine': 'Pizza',
  'CurrentDecalNumber': '40673117',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10001',
  'MostRecent_Longitude': -74.003334819511,
  'MostRecent_Latitude': 40.748818825881,
  'Grade': 'A',
  'MostRecentVendingLocation': '256 10 AVENUE'},
 {'EntityName': '10TH FL CATERING',
  'Cuisine': 'American',
  'CurrentDecalNumber': '50115677',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10019',
  'MostRecent_Longitude': -73.982310166816,
  'MostRecent_Latitude': 40.768266872208,
  'Grade': 'A',
  'MostRecentVendingLocation': '10 COLUMBUS CIRCLE'},
 {'EntityName': '10TH FL FOOD HALL ( DEUTSCHE BANK CAFE)',
  'Cuisine': 'Armenian',
  'CurrentDecalNumber': '50115654',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10019',
  'MostRecent_Longitude': -73.982310166816,
  'MostRecent_Latitude': 40.768266872208,
  'Grade': 'A',
  'MostRecentVendingLocation': '10 COLUMBUS CIRCLE'},
 {'EntityName': '10TH FLOOR CAFE',
  'Cuisine': 'American',
  'CurrentDecalNumber': '50147425',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10013',
  'MostRecent_Longitude': -74.007493567152,
  'MostRecent_Latitude': 40.726160604859,
  'Grade': 'A',
  'MostRecentVendingLocation': '310 HUDSON STREET'},
 {'EntityName': '11 HOWARD KITCHEN',
  'Cuisine': 'American',
  'CurrentDecalNumber': '50052807',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10013',
  'MostRecent_Longitude': -73.999953102562,
  'MostRecent_Latitude': 40.719076605989,
  'Grade': 'A',
  'MostRecentVendingLocation': '138 LAFAYETTE STREET'},
 {'EntityName': '11 STREET CAFE',
  'Cuisine': 'Coffee/Tea',
  'CurrentDecalNumber': '41217083',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10014',
  'MostRecent_Longitude': -74.007476594239,
  'MostRecent_Latitude': 40.735630046012,
  'Grade': 'A',
  'MostRecentVendingLocation': '327 WEST   11 STREET'},
 {'EntityName': '110 NUTRITION (HERBALIFE)',
  'Cuisine': 'Juice, Smoothies, Fruit Salads',
  'CurrentDecalNumber': '50105569',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10029',
  'MostRecent_Longitude': -73.940702500434,
  'MostRecent_Latitude': 40.793007853065,
  'Grade': 'A',
  'MostRecentVendingLocation': '2135 2 AVENUE'},
 {'EntityName': '1121 AOA COFFEE BAR',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50186688',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10036',
  'MostRecent_Longitude': -73.983566031532,
  'MostRecent_Latitude': 40.7556082347,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '1121 AVENUE OF THE AMERICAS'},
 {'EntityName': '11214',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50187610',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10009',
  'MostRecent_Longitude': -73.9807367498,
  'MostRecent_Latitude': 40.728840868481,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '515 EAST   12 STREET'},
 {'EntityName': '113 SPRING',
  'Cuisine': 'Vegan',
  'CurrentDecalNumber': '50174220',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10012',
  'MostRecent_Longitude': -73.999953099371,
  'MostRecent_Latitude': 40.72359449293,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '113 SPRING STREET'},
 {'EntityName': '11TH FL CLIENT DINING',
  'Cuisine': 'American',
  'CurrentDecalNumber': '50115657',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10019',
  'MostRecent_Longitude': -73.982310166816,
  'MostRecent_Latitude': 40.768266872208,
  'Grade': 'A',
  'MostRecentVendingLocation': '10 COLUMBUS CIRCLE'},
 {'EntityName': '11TH ST BAR',
  'Cuisine': 'American',
  'CurrentDecalNumber': '50084061',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10009',
  'MostRecent_Longitude': -73.981281738153,
  'MostRecent_Latitude': 40.728215152107,
  'Grade': 'A',
  'MostRecentVendingLocation': '510 EAST   11 STREET'},
 {'EntityName': '11TIGERS',
  'Cuisine': 'Asian/Asian Fusion',
  'CurrentDecalNumber': '50125105',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10009',
  'MostRecent_Longitude': -73.978286830292,
  'MostRecent_Latitude': 40.729054522613,
  'Grade': 'A',
  'MostRecentVendingLocation': '225 AVENUE B'},
 {'EntityName': '12 CHAIRS CATERING',
  'Cuisine': 'Mediterranean',
  'CurrentDecalNumber': '50140852',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10012',
  'MostRecent_Longitude': -74.001850890753,
  'MostRecent_Latitude': 40.72789003733,
  'Grade': 'A',
  'MostRecentVendingLocation': '142 WEST HOUSTON STREET'},
 {'EntityName': '12 CHAIRS SHUK LLC',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50174351',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10036',
  'MostRecent_Longitude': -73.982292294107,
  'MostRecent_Latitude': 40.754073724489,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '41 WEST   42 STREET'},
 {'EntityName': '12 MATCHA',
  'Cuisine': 'Coffee/Tea',
  'CurrentDecalNumber': '50169165',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10012',
  'MostRecent_Longitude': -73.992683242876,
  'MostRecent_Latitude': 40.725943779738,
  'Grade': 'A',
  'MostRecentVendingLocation': '54 BOND STREET'},
 {'EntityName': '120 E. 23RD STREET LOCATION LLC',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50179549',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10010',
  'MostRecent_Longitude': -73.985388698602,
  'MostRecent_Latitude': 40.73976571812,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '120 EAST   23 STREET'},
 {'EntityName': '123 MARKET PLACE',
  'Cuisine': 'American',
  'CurrentDecalNumber': '50110715',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10038',
  'MostRecent_Longitude': -74.006892888095,
  'MostRecent_Latitude': 40.709104653841,
  'Grade': 'A',
  'MostRecentVendingLocation': '123 WILLIAM STREET'},
 {'EntityName': '124 OLD RABBIT CLUB',
  'Cuisine': 'Bottled Beverages',
  'CurrentDecalNumber': '50137734',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10012',
  'MostRecent_Longitude': -74.000465443487,
  'MostRecent_Latitude': 40.730003520869,
  'Grade': 'A',
  'MostRecentVendingLocation': '124 MACDOUGAL STREET'},
 {'EntityName': '12TH ST. ALE HOUSE',
  'Cuisine': 'Bottled Beverages',
  'CurrentDecalNumber': '50086684',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10003',
  'MostRecent_Longitude': -73.985697258364,
  'MostRecent_Latitude': 40.731287180283,
  'Grade': 'A',
  'MostRecentVendingLocation': '192 2 AVENUE'},
 {'EntityName': '133 GREENWICH LLC',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50184859',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10006',
  'MostRecent_Longitude': -74.012930997635,
  'MostRecent_Latitude': 40.709460951991,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '133 GREENWICH STREET'},
 {'EntityName': '14 CHELSEA CORP.',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50187525',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10014',
  'MostRecent_Longitude': -74.003962298938,
  'MostRecent_Latitude': 40.740342980414,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '344 WEST   14 STREET'},
 {'EntityName': '15 EAST @ TOCQUEVILLE',
  'Cuisine': 'French',
  'CurrentDecalNumber': '41148766',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10003',
  'MostRecent_Longitude': -73.992801151252,
  'MostRecent_Latitude': 40.736560538802,
  'Grade': 'A',
  'MostRecentVendingLocation': '3 EAST   15 STREET'},
 {'EntityName': '1509 LEX AVE CORP',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50185169',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10029',
  'MostRecent_Longitude': -73.950259650517,
  'MostRecent_Latitude': 40.786759847663,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '1509 LEXINGTON AVENUE'},
 {'EntityName': '1530 TIME CHICKEN LLC',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50182712',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10036',
  'MostRecent_Longitude': -73.985121256364,
  'MostRecent_Latitude': 40.757667016401,
  'Grade': 'Not Yet Graded',
  'MostRecentVendingLocation': '1530 BROADWAY'},
 {'EntityName': '16 HANDLES',
  'Cuisine': 'Frozen Desserts',
  'CurrentDecalNumber': '50105549',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10007',
  'MostRecent_Longitude': -74.010172657064,
  'MostRecent_Latitude': 40.715947119217,
  'Grade': 'A',
  'MostRecentVendingLocation': '155 CHAMBERS STREET'},
 {'EntityName': '16 HANDLES',
  'Cuisine': 'Frozen Desserts',
  'CurrentDecalNumber': '50090528',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10016',
  'MostRecent_Longitude': -73.980083041804,
  'MostRecent_Latitude': 40.743050400951,
  'Grade': 'C',
  'MostRecentVendingLocation': '428 3 AVENUE'},
 {'EntityName': '16 HANDLES',
  'Cuisine': 'Frozen Desserts',
  'CurrentDecalNumber': '50096571',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10003',
  'MostRecent_Longitude': -73.987054283108,
  'MostRecent_Latitude': 40.729456582958,
  'Grade': 'A',
  'MostRecentVendingLocation': '153 2 AVENUE'},
 {'EntityName': '16 HANDLES',
  'Cuisine': 'Frozen Desserts',
  'CurrentDecalNumber': '50096572',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10011',
  'MostRecent_Longitude': -74.000202092303,
  'MostRecent_Latitude': 40.742917636188,
  'Grade': 'A',
  'MostRecentVendingLocation': '178 8 AVENUE'},
 {'EntityName': '16 HANDLES',
  'Cuisine': 'Frozen Desserts',
  'CurrentDecalNumber': '50130973',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10023',
  'MostRecent_Longitude': -73.980057280168,
  'MostRecent_Latitude': 40.78074415885,
  'Grade': 'A',
  'MostRecentVendingLocation': '325 AMSTERDAM AVENUE'},
 {'EntityName': '16 SOLA LLC',
  'Cuisine': 'Other',
  'CurrentDecalNumber': '50182127',
  'MostRecentVendingBoro': 'Manhattan',
  'MostRecentZipCode': '10001',

In [6]:
df_manhattan = pd.DataFrame(response.json())
df_manhattan

,EntityName,Cuisine,CurrentDecalNumber,MostRecentVendingBoro,MostRecentZipCode,MostRecent_Longitude,MostRecent_Latitude,Grade,MostRecentVendingLocation
0,"""U"" LIKE CHINESE TAKE OUT",Chinese,50126747,Manhattan,10034,-73.921726,40.867494,A,4926 BROADWAY
1,$1 PIZZA,Pizza,50117047,Manhattan,10014,-74.001176,40.731409,Grade Pending,333B AVENUE OF THE AMERICAS
2,$1 PIZZA,Pizza,50086385,Manhattan,10001,-73.990158,40.746510,A,832 6 AVENUE
3,$1.50 FRESH PIZZA,Pizza,50136410,Manhattan,10019,-73.982304,40.764515,A,1723 BROADWAY
4,$1.50 FRESH PIZZA,Pizza,50136412,Manhattan,10013,-74.004740,40.721426,A,383 CANAL STREET
...,...,...,...,...,...,...,...,...,...
12431,ZURNA,Middle Eastern,50137924,Manhattan,10025,-73.968291,40.799617,A,2715 BROADWAY
12432,ZURUTTO,Japanese,50078158,Manhattan,10023,-73.980289,40.778027,A,142 WEST 72 STREET
12433,ZUTTO,Japanese,50080253,Manhattan,10013,-74.008871,40.718382,A,77 HUDSON STREET
12434,ZUTTO JAPANESE AMERICAN BAR,Japanese,50119060,Manhattan,10013,-73.996598,40.720411,A,384 BROOME STREET
12435,ZZ CLAM BAR,Seafood,50001062,Manhattan,10012,-74.000336,40.727649,A,169 THOMPSON STREET

In [ ]:
df_manhattan.to_csv("manhattan_restaurant_inspections.csv", index = False)

Get all the boroughs

In [ ]:
# list of boros
boros = ["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten%20Island"]

In [ ]:
## slice boro
boros[2]

'Queens'

In [ ]:
## for loop thru boros
for boro in boros:
  print(f"This is {boro.upper()}")

This is MANHATTAN
This is BROOKLYN
This is QUEENS
This is BRONX
This is STATEN%20ISLAND

In [ ]:
url_placeholder = "https://a816-health.nyc.gov/ABCEatsRestaurants/App/GetEntitiesByBoro/"

In [ ]:
# iteragte to scrape all boros
df_list = [] # empty list to append dfs

for boro in boros: #iterate through boros
  url = f"{url_placeholder}{boro}" # create url
  print(url) # flag where i am
  response = requests.get(url) # grab url
  df_list.append(pd.DataFrame(response.json())) # append to empty list

https://a816-health.nyc.gov/ABCEatsRestaurants/App/GetEntitiesByBoro/Manhattan
https://a816-health.nyc.gov/ABCEatsRestaurants/App/GetEntitiesByBoro/Brooklyn
https://a816-health.nyc.gov/ABCEatsRestaurants/App/GetEntitiesByBoro/Queens
https://a816-health.nyc.gov/ABCEatsRestaurants/App/GetEntitiesByBoro/Bronx
https://a816-health.nyc.gov/ABCEatsRestaurants/App/GetEntitiesByBoro/Staten%20Island

In [ ]:
len(df_list)

5

In [ ]:
df_list[3]

,Cuisine,CurrentDecalNumber,MostRecentVendingBoro,MostRecentZipCode,MostRecent_Longitude,MostRecent_Latitude,Grade,MostRecentVendingLocation,EntityName
0,Other,50184694,Bronx,10458,-73.886437,40.857600,Not Yet Graded,585 EAST 189 STREET,NaN
1,Latin American,41336841,Bronx,10466,-73.858591,40.891176,A,4120 WHITE PLAINS ROAD,#1 SABOR LATINO RESTAURANT
2,Pizza,50138727,Bronx,10467,-73.882900,40.881253,Grade Pending,3414 JEROME AVENUE,$1 SLICE PIZZA
3,"Juice, Smoothies, Fruit Salads",41316782,Bronx,10452,-73.914536,40.844244,A,6 EAST MT EDEN AVENUE,1 BANANA QUEEN
4,Pizza,50068084,Bronx,10455,-73.917983,40.815649,A,526A WILLIS AVENUE,1.50 HOT PIZZA
...,...,...,...,...,...,...,...,...,...
2624,Other,50188094,Bronx,10456,-73.907539,40.836002,Not Yet Graded,1387 WEBSTER AVENUE,ZEST CHICKEN LLC
2625,Asian/Asian Fusion,50108565,Bronx,10458,-73.884407,40.856583,A,657 EAST 189 STREET,ZHONG ZHONG NOODLES
2626,Chinese,50146557,Bronx,10459,-73.891310,40.826792,A,971 EAST 167 STREET,ZHU'S KITCHEN
2627,Latin American,50093661,Bronx,10451,-73.927062,40.819064,B,558 GRAND CONCOURSE,ZONA DE CUBA
2628,American,40368021,Bronx,10460,-73.882455,40.850537,A,2300 SOUTHERN BOULEVARD,ZOO BREWS-BRONX ZOO

In [ ]:
df = pd.concat(df_list, ignore_index = True )

In [ ]:
df

,EntityName,Cuisine,CurrentDecalNumber,MostRecentVendingBoro,MostRecentZipCode,MostRecent_Longitude,MostRecent_Latitude,Grade,MostRecentVendingLocation
0,"""U"" LIKE CHINESE TAKE OUT",Chinese,50126747,Manhattan,10034,-73.921726,40.867494,A,4926 BROADWAY
1,$1 PIZZA,Pizza,50117047,Manhattan,10014,-74.001176,40.731409,Grade Pending,333B AVENUE OF THE AMERICAS
2,$1 PIZZA,Pizza,50086385,Manhattan,10001,-73.990158,40.746510,A,832 6 AVENUE
3,$1.50 FRESH PIZZA,Pizza,50136410,Manhattan,10019,-73.982304,40.764515,A,1723 BROADWAY
4,$1.50 FRESH PIZZA,Pizza,50136412,Manhattan,10013,-74.004740,40.721426,A,383 CANAL STREET
...,...,...,...,...,...,...,...,...,...
31106,ZARA ARTHUR MEDITERRANEAN CUISINE,Mediterranean,50158658,Staten Island,10312,-74.168998,40.560902,A,854 ARTHUR KILL ROAD
31107,ZARA CAFE GRILL,Turkish,50070120,Staten Island,10306,-74.098266,40.581384,A,1995 HYLAN BOULEVARD
31108,ZARA FOREST,Turkish,50133239,Staten Island,10303,-74.147129,40.624954,Grade Pending,1745 FOREST AVENUE
31109,ZINGER HALAL EXPRESS,Chicken,50141303,Staten Island,10314,-74.129482,40.612539,A,1970 VICTORY BOULEVARD
31110,ZZ'S PIZZA & GRILL,Pizza,41702705,Staten Island,10301,-74.073319,40.643868,B,1 RICHMOND TERRACE